# -*- coding: utf-8 -*-
"""week1_saksham_saraogi_jecrc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6Mrd__Lj8EHqb4OW6nb_flQTUCgzf4e

# 📘 Week 1 Assignment — ML Foundations

**Topics Covered:** Python · NumPy · Pandas · Linear Algebra · Statistics · Probability Theory

---

> Complete all cells. Where marked `# YOUR CODE HERE`, write your solution. Do not change cell types or remove assertion blocks.
"""

# ── Setup ──────────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
from io import StringIO

plt.rcParams['figure.figsize'] = (9, 4)
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
print('All imports OK ✓')

"""---
## Part 1 — Python Fundamentals

### 1.1 Data Types & Control Flow

Write a function `classify_number(n)` that:
- Returns `"negative"` if `n < 0`
- Returns `"zero"` if `n == 0`
- Returns `"small positive"` if `0 < n <= 10`
- Returns `"large positive"` otherwise
"""

def classify_number(n):
    if n < 0:
        return "negative"
    elif n == 0:
        return "zero"
    elif 0 < n <= 10:
        return "small positive"
    else:
        return "large positive"

# Tests
assert classify_number(-5) == "negative"
assert classify_number(0)  == "zero"
assert classify_number(7)  == "small positive"
assert classify_number(42) == "large positive"
print("1.1 passed ✓")

"""### 1.2 Data Structures

Given the list `words = ['apple', 'banana', 'cherry', 'apple', 'date', 'banana', 'apple']`:

1. Build a **dict** `word_count` mapping each word to its frequency using only a loop (no `Counter`).
2. Using a **set**, find all unique words and store in `unique_words`.
3. Using a **list comprehension**, build `long_words` containing words with more than 5 characters.
"""

words = ['apple', 'banana', 'cherry', 'apple', 'date', 'banana', 'apple']

# 1. word_count dict
word_count = {}
for w in words:
    word_count[w] = word_count.get(w, 0) + 1

# 2. unique_words set
unique_words = set(words)

# 3. long_words list comprehension
long_words = [w for w in words if len(w) > 5]

# Tests
assert word_count == {'apple': 3, 'banana': 2, 'cherry': 1, 'date': 1}
assert unique_words == {'apple', 'banana', 'cherry', 'date'}
assert set(long_words) == {'banana', 'cherry'}
print("1.2 passed ✓")

"""### 1.3 Exceptions

Write `safe_divide(a, b)` that:
- Returns `a / b` normally
- Returns `None` if `b == 0` (catch `ZeroDivisionError`)
- Raises `TypeError` with message `"Inputs must be numeric"` if either input is not a number
"""

def safe_divide(a, b):
    if not (isinstance(a, (int, float)) and isinstance(b, (int, float))):
        raise TypeError("Inputs must be numeric")
    try:
        return a / b
    except ZeroDivisionError:
        return None

# Tests
assert safe_divide(10, 2) == 5.0
assert safe_divide(5, 0) is None
try:
    safe_divide('x', 2)
    assert False, "Should have raised TypeError"
except TypeError as e:
    assert str(e) == "Inputs must be numeric"
print("1.3 passed ✓")

"""def apply_twice(f, x):
    return f(f(x))

triple = lambda x: x * 3

result = apply_twice(triple, 4)
assert result == 36, f"Expected 36, got {result}"
print("1.4 passed ✓")

"""

def apply_twice(f, x):
    return f(f(x))

triple = lambda x: x * 3

result = apply_twice(triple, 4)
assert result == 36, f"Expected 36, got {result}"
print("1.4 passed ✓")

"""---
## Part 2 — NumPy

### 2.1 Array Creation & Shapes

1. Create a 1D array `arr1d` of integers 0–11.
2. Reshape it into a 2D array `arr2d` of shape `(3, 4)`.
3. Reshape `arr1d` into a 3D array `arr3d` of shape `(2, 2, 3)`.
4. Print the shape, ndim, and dtype of each.
"""

arr1d = np.arange(12)
arr2d = arr1d.reshape(3, 4)
arr3d = arr1d.reshape(2, 2, 3)

# Tests
assert arr1d.shape == (12,)
assert arr2d.shape == (3, 4)
assert arr3d.shape == (2, 2, 3)
print("2.1 passed ✓")
print(f"arr2d:\n{arr2d}")
print(f"arr3d:\n{arr3d}")

"""### 2.2 Indexing & Slicing

Using `arr2d` from above:
1. Extract the **second row** → `row2`
2. Extract the **third column** → `col3`
3. Extract the **bottom-right 2×2 submatrix** → `sub`
4. Use **boolean indexing** to get all elements greater than 7 → `gt7`
"""

row2 = arr2d[1]
col3 = arr2d[:, 2]
sub  = arr2d[1:, 2:]
gt7  = arr2d[arr2d > 7]

# Tests
assert list(row2) == [4, 5, 6, 7]
assert list(col3) == [2, 6, 10]
assert sub.shape == (2, 2)
assert list(gt7) == [8, 9, 10, 11]
print("2.2 passed ✓")

"""### 2.3 Operations & Dot Product

Given:
```
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
```

1. Compute **element-wise product** `C = A * B`
2. Compute **matrix multiplication** `D = A @ B`
3. Compute the **dot product** of vectors `[1,2,3]` and `[4,5,6]` → `dp`
4. Multiply all elements of `A` by scalar 3 → `E`
"""

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C  = A * B                                          # element-wise product
D  = A @ B                                          # matrix multiplication
dp = np.dot(np.array([1, 2, 3]), np.array([4, 5, 6]))  # dot product
E  = A * 3                                          # scalar multiplication

# Tests
assert np.array_equal(C, [[5,12],[21,32]])
assert np.array_equal(D, [[19,22],[43,50]])
assert dp == 32
assert np.array_equal(E, [[3,6],[9,12]])
print("2.3 passed ✓")

"""---
## Part 3 — Pandas
"""

# Load dataset — do not modify this cell
CSV_DATA = """employee_id,name,department,salary,age,years_exp,performance
1,Alice,Engineering,95000,30,5,4.2
2,Bob,Marketing,72000,35,8,3.8
3,Carol,Engineering,88000,28,3,4.5
4,Dave,HR,61000,42,15,3.1
5,Eve,Engineering,102000,38,12,4.8
6,Frank,Marketing,68000,29,4,3.5
7,Grace,HR,,31,6,3.9
8,Hank,Engineering,91000,45,20,4.1
9,Iris,Marketing,75000,,7,4.0
10,Jack,Engineering,85000,33,8,
"""
df = pd.read_csv(StringIO(CSV_DATA))
print(f"Shape: {df.shape}")
df.head()

"""### 3.1 DataFrames vs Series

1. Extract the `salary` column as a **Series** → `salary_series`
2. Extract `name` and `department` columns as a **DataFrame** → `name_dept_df`
3. Print the type of each to confirm.
"""

salary_series = df['salary']
name_dept_df  = df[['name', 'department']]

assert isinstance(salary_series, pd.Series)
assert isinstance(name_dept_df, pd.DataFrame)
print(f"salary_series type: {type(salary_series).__name__}")
print(f"name_dept_df type: {type(name_dept_df).__name__}")
print("3.1 passed ✓")

"""### 3.2 iloc & loc

1. Use `iloc` to select rows 2–4 (inclusive), columns 0–2 → `iloc_result`
2. Use `loc` to select rows where index is 5 or 6, columns `name` and `salary` → `loc_result`
"""

iloc_result = df.iloc[2:5, 0:3]
loc_result  = df.loc[5:6, ['name', 'salary']]

assert iloc_result.shape == (3, 3)
assert list(loc_result.columns) == ['name', 'salary']
print("3.2 passed ✓")
display(iloc_result)
display(loc_result)

"""### 3.3 Filtering & Group By

1. Filter employees in **Engineering** with **salary > 90000** → `senior_eng`
2. Group by `department` and compute mean salary and mean performance → `dept_stats`
3. Sort `dept_stats` by mean salary descending.
"""

senior_eng = df[(df['department'] == 'Engineering') & (df['salary'] > 90000)]
dept_stats = (df.groupby('department')
                .agg(mean_salary=('salary', 'mean'), mean_performance=('performance', 'mean'))
                .sort_values('mean_salary', ascending=False))

print(f"Senior engineers: {len(senior_eng)}")
display(senior_eng[['name', 'salary']])
print("\nDept stats:")
display(dept_stats)

"""### 3.4 Handling Missing Data

1. Identify which columns have missing values and how many → print a summary.
2. Fill missing `salary` with the **median salary** → `df_filled`
3. Fill missing `age` with the **mean age** (rounded to nearest int).
4. Drop rows where `performance` is missing.
5. Confirm no nulls remain.
"""

print("Missing values before:")
print(df.isnull().sum())

df_filled = df.copy()
median_salary = df_filled['salary'].median()
mean_age      = round(df_filled['age'].mean())

df_filled['salary'] = df_filled['salary'].fillna(median_salary)
df_filled['age']    = df_filled['age'].fillna(mean_age)
df_filled           = df_filled.dropna(subset=['performance'])

print("\nMissing values after:")
print(df_filled.isnull().sum())
assert df_filled.isnull().sum().sum() == 0, "Still has nulls!"
print("3.4 passed ✓")

"""---
## Part 4 — Linear Algebra

v = np.array([3, 4])
norm_v = np.linalg.norm(v)
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Plot
fig, ax = plt.subplots()
ax.quiver(0, 0, v[0], v[1], angles='xy', scale_units='xy', scale=1, color='royalblue')
ax.set_xlim(-1, 5); ax.set_ylim(-1, 5)
ax.set_xlabel('x'); ax.set_ylabel('y')
ax.set_title('Vector Visualization')
ax.axhline(0, color='k', lw=0.8); ax.axvline(0, color='k', lw=0.8)
plt.tight_layout(); plt.show()

assert abs(norm_v - 5.0) < 1e-9
assert M.shape == (3, 3)
print(f"4.1 passed ✓  |v| = {norm_v}")
"""

v = np.array([3, 4])
norm_v = np.linalg.norm(v)
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Plot
fig, ax = plt.subplots()
ax.quiver(0, 0, v[0], v[1], angles='xy', scale_units='xy', scale=1, color='royalblue')
ax.set_xlim(-1, 5); ax.set_ylim(-1, 5)
ax.set_xlabel('x'); ax.set_ylabel('y')
ax.set_title('Vector Visualization')
ax.axhline(0, color='k', lw=0.8); ax.axvline(0, color='k', lw=0.8)
plt.tight_layout(); plt.show()

assert abs(norm_v - 5.0) < 1e-9
assert M.shape == (3, 3)
print(f"4.1 passed ✓  |v| = {norm_v}")

"""### 4.2 Matrix Operations in Practice

Let:
```
P = [[2, 1], [0, 3]]
Q = [[1, 4], [2, 0]]
```

1. Compute `P + Q` (matrix addition)
2. Compute `3 * P` (scalar multiplication)
3. Compute `P @ Q` (matrix multiplication)
4. Verify that matrix multiplication is **not commutative** — show `P @ Q ≠ Q @ P`.
"""

P = np.array([[2, 1], [0, 3]])
Q = np.array([[1, 4], [2, 0]])

PplusQ   = P + Q
scalar3P = 3 * P
PQ       = P @ Q
QP       = Q @ P

print(f"P + Q =\n{PplusQ}")
print(f"3*P =\n{scalar3P}")
print(f"P @ Q =\n{PQ}")
print(f"Q @ P =\n{QP}")
print(f"PQ == QP? {np.array_equal(PQ, QP)}")

assert not np.array_equal(PQ, QP), "They should differ!"
print("4.2 passed ✓")

"""### 4.3 Eigenvalues & Eigenvectors

For the matrix:
```
A = [[4, 1],
     [2, 3]]
```

1. Compute eigenvalues and eigenvectors using `np.linalg.eig`.
2. **Verify** the eigenvector equation: `A @ v = λ * v` for each eigenpair.
3. Plot both eigenvectors as arrows, scaled by their eigenvalues, on a 2D plot.
4. **Explain** in a markdown cell (below): what does it geometrically mean for a matrix to stretch a vector?
"""

A = np.array([[4, 1], [2, 3]], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors (columns):\n{eigenvectors}")

# Verify Av = λv for each eigenpair
for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    vec = eigenvectors[:, i]
    assert np.allclose(A @ vec, lam * vec)
    print(f"  λ={lam:.2f}:  A@v ≈ λv  ✓")

# Plot eigenvectors scaled by their eigenvalues
fig, ax = plt.subplots()
colors = ['red', 'green']
for i in range(2):
    v_e = eigenvectors[:, i] * eigenvalues[i]
    ax.quiver(0, 0, v_e[0], v_e[1], angles='xy', scale_units='xy', scale=1,
              color=colors[i], label=f"λ={eigenvalues[i]:.1f}")
ax.set_xlim(-4, 4); ax.set_ylim(-4, 4)
ax.axhline(0, color='k', lw=0.5); ax.axvline(0, color='k', lw=0.5)
ax.legend(); ax.set_title('Eigenvectors scaled by Eigenvalues')
plt.tight_layout(); plt.show()

print("4.3 passed ✓")

"""**Your Geometric Explanation (4.3):**

> An **eigenvector** of a matrix is a special direction that the matrix does not rotate — it only *scales* that vector. The **eigenvalue** is the scale factor: λ > 1 stretches the vector, 0 < λ < 1 shrinks it, λ < 0 flips and scales it, and λ = 0 collapses it to zero. Together, eigenvectors reveal the "natural axes" of a transformation — the directions along which the matrix acts most simply (pure stretching/squishing), with no rotation component.

### 4.4 SVD & Dimensionality Reduction

1. Create a random 4×3 matrix `X` (use `np.random.seed(42)`).
2. Compute its **SVD**: `U, S, Vt = np.linalg.svd(X, full_matrices=False)`.
3. **Reconstruct** `X` from the SVD and verify it matches the original.
4. Perform a **rank-1 approximation** using only the largest singular value/vector — call it `X_approx`.
5. Explain the relationship between SVD components and PCA in the markdown cell below.
"""

np.random.seed(42)
X = np.random.randn(4, 3)

U, S, Vt = np.linalg.svd(X, full_matrices=False)

X_reconstructed = U @ np.diag(S) @ Vt                  # full reconstruction
X_approx        = S[0] * np.outer(U[:, 0], Vt[0, :])   # rank-1 approximation

print(f"U shape: {U.shape}, S shape: {S.shape}, Vt shape: {Vt.shape}")
print(f"Singular values: {S}")
print(f"Reconstruction error: {np.linalg.norm(X - X_reconstructed):.2e}")
print(f"Rank-1 approximation:\n{X_approx}")

assert np.allclose(X, X_reconstructed, atol=1e-10), "Reconstruction failed!"
print("4.4 passed ✓")

"""**SVD → PCA Connection (4.4):**

> In SVD of a mean-centred matrix X = U S Vᵀ:
> - **Vt (rows)** — the **right singular vectors** — are exactly the **principal component directions** (axes of maximum variance in input space).
> - **S** — the **singular values** — are proportional to √(variance explained) by each component.
> - **U** — the **left singular vectors** — are the normalised projections of the data onto those directions; scaling by S gives the PC scores.
>
> PCA on X is therefore identical to computing its SVD. The matrix containing the directions of maximum variance is **Vt**.

---
## Part 5 — Statistics

### 5.1 Descriptive vs Inferential Statistics

Using the cleaned `df_filled` from Part 3:

1. Compute **descriptive statistics** for the `salary` column: mean, median, std, min, max, IQR.
2. Plot a **histogram** of salary with a KDE overlay.
3. In the markdown cell below, write one sentence each defining: *population*, *sample*, *descriptive statistic*, *inferential statistic*.
"""

salary = df_filled['salary']

mean_s   = salary.mean()
median_s = salary.median()
std_s    = salary.std()
min_s    = salary.min()
max_s    = salary.max()
iqr_s    = np.percentile(salary, 75) - np.percentile(salary, 25)

print(f"Mean:   {mean_s:.0f}")
print(f"Median: {median_s:.0f}")
print(f"Std:    {std_s:.0f}")
print(f"Range:  {min_s:.0f} – {max_s:.0f}")
print(f"IQR:    {iqr_s:.0f}")

# Histogram + KDE
fig, ax = plt.subplots()
ax.hist(salary, bins=6, density=True, alpha=0.6, color='steelblue', label='Histogram')
xr = np.linspace(salary.min(), salary.max(), 200)
kde = stats.gaussian_kde(salary)
ax.plot(xr, kde(xr), color='red', lw=2, label='KDE')
ax.legend()
ax.set_xlabel('Salary'); ax.set_title('Salary Distribution')
plt.tight_layout(); plt.show()

"""**Definitions (5.1):**

- **Population:** The complete set of all individuals or observations of interest (e.g., all employees in the company).
- **Sample:** A subset drawn from the population that is used to estimate properties of the whole.
- **Descriptive statistic:** A numerical summary (mean, median, std, IQR) that describes characteristics of the observed data without making inferences beyond it.
- **Inferential statistic:** A method that uses sample data to draw conclusions, test hypotheses, or make predictions about the broader population (e.g., t-tests, confidence intervals).

### 5.2 Hypothesis Testing

**Scenario:** You suspect that Engineering salaries are significantly higher than the company average.

1. State the **null hypothesis H₀** and **alternative hypothesis H₁**.
2. Run a **one-sample t-test** comparing Engineering salaries against the overall mean salary.
3. Interpret the p-value at α = 0.05.
4. Also compute the **Pearson correlation** between `salary` and `years_exp`, and interpret it.
"""

eng_salaries = df_filled[df_filled['department'] == 'Engineering']['salary']
overall_mean = df_filled['salary'].mean()

# One-sample t-test
t_stat, p_value = stats.ttest_1samp(eng_salaries, overall_mean)

print(f"Overall mean salary: {overall_mean:.0f}")
print(f"Engineering mean salary: {eng_salaries.mean():.0f}")
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print(f"Reject H0 at α=0.05? {p_value < 0.05}")

# Pearson correlation
r, r_pval = stats.pearsonr(df_filled['salary'], df_filled['years_exp'])
print(f"\nPearson r (salary vs years_exp): {r:.4f}, p={r_pval:.4f}")

"""**H₀ / H₁ and Interpretation (5.2):**

- **H₀:** Engineering salaries are equal to the company-wide mean (μ_eng = μ_overall).
- **H₁:** Engineering salaries are greater than the company-wide mean (μ_eng > μ_overall).
- **Conclusion:** p ≈ 0.028 < 0.05 → we **reject H₀**. There is statistically significant evidence that Engineering salaries are higher than average. The Pearson r between salary and years_exp is ≈ 0.05 (p ≈ 0.90), indicating no meaningful linear correlation in this small sample.

### 5.3 Error Metrics

Given these predictions and actuals, **implement from scratch** (no sklearn):
- MAE, MSE, RMSE
- R² Score
- Adjusted R² (assume 2 features)
"""

y_true = np.array([3.0, 5.0, 2.5, 7.0, 4.5, 6.0, 1.5, 8.0])
y_pred = np.array([2.8, 5.2, 2.1, 7.5, 4.0, 6.3, 2.0, 7.8])
n, p = len(y_true), 2

mae    = np.mean(np.abs(y_true - y_pred))
mse    = np.mean((y_true - y_pred) ** 2)
rmse   = np.sqrt(mse)
ss_res = np.sum((y_true - y_pred) ** 2)
ss_tot = np.sum((y_true - y_true.mean()) ** 2)
r2     = 1 - ss_res / ss_tot
adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

print(f"MAE:        {mae:.4f}")
print(f"MSE:        {mse:.4f}")
print(f"RMSE:       {rmse:.4f}")
print(f"R²:         {r2:.4f}")
print(f"Adj. R²:    {adj_r2:.4f}")

"""### 5.4 Distribution Testing & Stationarity

1. Generate two samples: `s1` ~ Normal(0, 1), `s2` ~ Exponential(1), both n=200 (seed=0).
2. Run the **Kolmogorov-Smirnov test** (`stats.kstest`) comparing each against a standard normal CDF.
3. Generate a non-stationary time series (linear trend + noise). Run the **Augmented Dickey-Fuller test** (`adfuller` from `statsmodels`) and interpret the result.
4. Difference the series once and re-run ADF to confirm stationarity.
"""

from statsmodels.tsa.stattools import adfuller

np.random.seed(0)
s1 = np.random.normal(0, 1, 200)
s2 = np.random.exponential(1, 200)

# KS test — compare each against N(0,1)
ks_s1 = stats.kstest(s1, 'norm')
ks_s2 = stats.kstest(s2, 'norm')
print(f"KS test s1 (normal):      stat={ks_s1.statistic:.4f}, p={ks_s1.pvalue:.4f}")
print(f"KS test s2 (exponential): stat={ks_s2.statistic:.4f}, p={ks_s2.pvalue:.4f}")

# ADF test on non-stationary series
t = np.arange(200)
ts = 0.05 * t + np.random.normal(0, 1, 200)

adf_result = adfuller(ts)
print(f"\nADF statistic: {adf_result[0]:.4f}")
print(f"ADF p-value:   {adf_result[1]:.4f}")
print(f"Stationary?    {adf_result[1] < 0.05}")

# Difference once and re-run
ts_diff  = np.diff(ts)
adf_diff = adfuller(ts_diff)
print(f"\nAfter differencing — p-value: {adf_diff[1]:.4f}, Stationary? {adf_diff[1] < 0.05}")

"""def compute_psi(expected, actual, bins=10):
    '''
    PSI = sum((actual_pct - expected_pct) * ln(actual_pct / expected_pct))
    Add epsilon=1e-10 to avoid log(0).
    '''
    eps = 1e-10
    breakpoints = np.linspace(min(expected.min(), actual.min()),
                               max(expected.max(), actual.max()), bins + 1)
    exp_counts, _ = np.histogram(expected, bins=breakpoints)
    act_counts, _ = np.histogram(actual,   bins=breakpoints)
    exp_pct = exp_counts / len(expected) + eps
    act_pct = act_counts / len(actual)   + eps
    return np.sum((act_pct - exp_pct) * np.log(act_pct / exp_pct))

np.random.seed(1)
train_dist = np.random.normal(50, 10, 1000)
drift_dist = np.random.normal(65, 12, 1000)

psi_value = compute_psi(train_dist, drift_dist)
print(f"PSI: {psi_value:.4f}")
print(f"Shift severity: {'Major' if psi_value > 0.2 else 'Minor' if psi_value > 0.1 else 'Stable'}")

# Plot both distributions
fig, ax = plt.subplots()
ax.hist(train_dist, bins=30, alpha=0.5, density=True, label='Training (μ=50)')
ax.hist(drift_dist, bins=30, alpha=0.5, density=True, label='Production (μ=65)')
ax.legend(); ax.set_title('Distribution Shift Visualization')
plt.tight_layout(); plt.show()

"""

def compute_psi(expected, actual, bins=10):
    """
    PSI = sum((actual_pct - expected_pct) * ln(actual_pct / expected_pct))
    Add epsilon=1e-10 to avoid log(0).
    """
    eps = 1e-10
    breakpoints = np.linspace(min(expected.min(), actual.min()),
                               max(expected.max(), actual.max()), bins + 1)
    exp_counts, _ = np.histogram(expected, bins=breakpoints)
    act_counts, _ = np.histogram(actual,   bins=breakpoints)
    exp_pct = exp_counts / len(expected) + eps
    act_pct = act_counts / len(actual)   + eps
    return np.sum((act_pct - exp_pct) * np.log(act_pct / exp_pct))

np.random.seed(1)
train_dist = np.random.normal(50, 10, 1000)    # training distribution
drift_dist = np.random.normal(65, 12, 1000)    # shifted production distribution

psi_value = compute_psi(train_dist, drift_dist)
print(f"PSI: {psi_value:.4f}")
print(f"Shift severity: {'Major' if psi_value > 0.2 else 'Minor' if psi_value > 0.1 else 'Stable'}")

# Plot both distributions
fig, ax = plt.subplots()
ax.hist(train_dist, bins=30, alpha=0.5, density=True, label="Training (μ=50)")
ax.hist(drift_dist, bins=30, alpha=0.5, density=True, label="Production (μ=65)")
ax.legend(); ax.set_title("Distribution Shift Visualization")
plt.tight_layout(); plt.show()

"""**Concept Drift vs Covariate Drift & PSI Thresholds (5.5):**

- **Concept drift:** The statistical relationship between features and the target changes over time (e.g., the words that predict spam evolve as spammers adapt).
- **Covariate drift:** The distribution of input features shifts while the feature→target relationship stays the same (e.g., user ages skew younger after a new product launch).
- **PSI < 0.1:** No significant shift — model is stable, no action needed.
- **PSI 0.1–0.2:** Minor shift — increase monitoring frequency, investigate root cause.
- **PSI > 0.2:** Major shift — investigate immediately and likely retrain the model.
- **Retraining trigger example:** Automatically queue a retraining job whenever the weekly PSI on any top-10 feature exceeds 0.2 in the production monitoring pipeline.

---
## Part 6 — Probability Theory

### 6.1 Core Concepts

A bag contains: 4 red, 3 blue, 3 green marbles.

1. Define the sample space and compute P(red), P(blue), P(green).
2. Two marbles drawn **without replacement**. Compute:
   - P(first=red, second=blue) — **joint probability**
   - P(second=blue | first=red) — **conditional probability**
3. Are the two draws **independent**? Show mathematically.
"""

total = 10
red, blue, green = 4, 3, 3

p_red   = red   / total
p_blue  = blue  / total
p_green = green / total

# Joint: P(red first AND blue second)
p_red_then_blue  = (red / total) * (blue / (total - 1))

# Conditional: P(blue second | red first)
p_blue_given_red = blue / (total - 1)

# Independence check: P(B|A) == P(B) ?
independent = (p_blue_given_red == p_blue)

print(f"P(red)={p_red:.3f}, P(blue)={p_blue:.3f}, P(green)={p_green:.3f}")
print(f"P(red,blue): {p_red_then_blue:.4f}")
print(f"P(blue|red): {p_blue_given_red:.4f}")
print(f"P(blue):     {p_blue:.4f}")
print(f"Independent? {independent}")

"""### 6.2 Distributions in the Wild

1. **Normal**: Plot N(μ=0, σ=1) and N(μ=2, σ=0.5) PDFs on the same axes.
2. **Binomial**: A coin is flipped 20 times. Plot the PMF for k=0..20 with p=0.5 and p=0.7.
3. **Poisson**: Average 3 customers/minute. Plot the PMF for k=0..15.
4. For each, write one real-world ML use case in comments.
"""

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# ── Normal ──────────────────────────────────────────────────────────────────
x = np.linspace(-4, 6, 300)
axes[0].plot(x, stats.norm.pdf(x, 0, 1),   label='N(μ=0, σ=1)')
axes[0].plot(x, stats.norm.pdf(x, 2, 0.5), label='N(μ=2, σ=0.5)')
axes[0].legend(); axes[0].set_title('Normal Distribution')
# ML use case: modelling residuals in linear regression; weight initialisation

# ── Binomial ────────────────────────────────────────────────────────────────
k = np.arange(0, 21)
axes[1].bar(k - 0.2, stats.binom.pmf(k, 20, 0.5), width=0.4, label='p=0.5')
axes[1].bar(k + 0.2, stats.binom.pmf(k, 20, 0.7), width=0.4, label='p=0.7', alpha=0.8)
axes[1].legend(); axes[1].set_title('Binomial Distribution')
# ML use case: number of correct predictions in n trials; Bernoulli output layer

# ── Poisson ─────────────────────────────────────────────────────────────────
k2 = np.arange(0, 16)
axes[2].bar(k2, stats.poisson.pmf(k2, 3))
axes[2].set_title('Poisson Distribution')
# ML use case: modelling rare events — fraud transactions, defect counts

plt.tight_layout(); plt.show()

"""p_spam            = 0.30
p_free_given_spam = 0.80
p_free_given_ham  = 0.05
p_ham             = 1 - p_spam

# P(free) — law of total probability
p_free = p_free_given_spam * p_spam + p_free_given_ham * p_ham

# Bayes
p_spam_given_free = (p_free_given_spam * p_spam) / p_free

print(f"P('free'): {p_free:.4f}")
print(f"P(Spam | 'free'): {p_spam_given_free:.4f}")

def naive_bayes_predict(prior_spam, p_word_given_spam, p_word_given_ham):
    prior_ham = 1 - prior_spam
    evidence  = p_word_given_spam * prior_spam + p_word_given_ham * prior_ham
    return (p_word_given_spam * prior_spam) / evidence

pred = naive_bayes_predict(0.30, 0.80, 0.05)
assert abs(pred - p_spam_given_free) < 1e-9
print(f"naive_bayes_predict: {pred:.4f}")
print("6.3 passed ✓")

"""

p_spam            = 0.30
p_free_given_spam = 0.80
p_free_given_ham  = 0.05
p_ham             = 1 - p_spam

# P(free) — law of total probability
p_free = p_free_given_spam * p_spam + p_free_given_ham * p_ham

# Bayes
p_spam_given_free = (p_free_given_spam * p_spam) / p_free

print(f"P(free): {p_free:.4f}")
print(f"P(Spam | free): {p_spam_given_free:.4f}")

def naive_bayes_predict(prior_spam, p_word_given_spam, p_word_given_ham):
    prior_ham = 1 - prior_spam
    evidence  = p_word_given_spam * prior_spam + p_word_given_ham * prior_ham
    return (p_word_given_spam * prior_spam) / evidence

pred = naive_bayes_predict(0.30, 0.80, 0.05)
assert abs(pred - p_spam_given_free) < 1e-9
print(f"naive_bayes_predict: {pred:.4f}")
print("6.3 passed ✓")

"""**Bayes Term Mapping (6.3):**

| Term | Formula | In this example |
|------|---------|-----------------|
| Prior | P(Spam) | 0.30 — baseline belief that any email is spam before seeing its content |
| Likelihood | P(word \| Spam) | P("free" \| Spam) = 0.80 — how often the word "free" appears in spam emails |
| Evidence | P(word) | P("free") = 0.275 — overall probability of "free" appearing in any email |
| Posterior | P(Spam \| word) | P(Spam \| "free") ≈ 0.8727 — updated probability the email is spam given it contains "free" |

### 6.4 Central Limit Theorem

1. Define a population following an **exponential distribution** (λ=1, size=100,000).
2. Repeatedly draw samples of size `n=30` and record their means — do this 5,000 times.
3. Plot the histogram of sample means.
4. Overlay the **theoretical normal distribution** predicted by the CLT: μ = population mean, σ = population_std / sqrt(n).
5. Run a KS test to confirm the distribution of sample means is approximately normal.
"""

np.random.seed(7)
population = np.random.exponential(scale=1.0, size=100_000)

n_samples   = 5000
sample_size = 30
sample_means = np.array([
    np.random.choice(population, size=sample_size, replace=False).mean()
    for _ in range(n_samples)
])

pop_mean = population.mean()
pop_std  = population.std()
clt_std  = pop_std / np.sqrt(sample_size)

print(f"Population mean: {pop_mean:.4f}, Population std: {pop_std:.4f}")
print(f"Sample means mean: {sample_means.mean():.4f}, std: {sample_means.std():.4f}")
print(f"CLT predicted std: {clt_std:.4f}")

# Plot
fig, ax = plt.subplots()
ax.hist(sample_means, bins=50, density=True, alpha=0.6, label='Sample means')
xr = np.linspace(sample_means.min(), sample_means.max(), 300)
ax.plot(xr, stats.norm.pdf(xr, pop_mean, clt_std), 'r-', lw=2, label='Theoretical normal')
ax.legend(); ax.set_title('CLT: Distribution of Sample Means')
plt.tight_layout(); plt.show()

# KS test
ks_result = stats.kstest(sample_means, 'norm', args=(pop_mean, clt_std))
print(f"KS test p-value: {ks_result.pvalue:.4f} → Approximately normal? {ks_result.pvalue > 0.05}")

"""**CLT Reflection (6.4):**

> I was honestly surprised when I saw the output. The original data was exponential and clearly skewed, but the sample means formed a normal distribution. I had to look at the plot twice.
So even if your data is messy or skewed, if you keep taking sample averages, those averages will start looking normal. Thats why t-tests and confidence intervals still work on real world data.
Never really understood why we could "just assume normality" before this. Now it makes sense.

---
## 🏁 Submission Checklist

Before submitting, verify:

- [ ] All `assert` blocks pass without errors
- [ ] All `# YOUR CODE HERE` cells are filled
- [ ] All markdown reflection cells are filled in your own words
- [ ] All plots render with labels and titles
- [ ] Notebook runs cleanly from top to bottom (`Kernel → Restart & Run All`)

**Save as:** `week1_<your_name>.ipynb`
"""